### ISSUE TITLE
Not correct time between laptop's time and NTPClient's time!

### ISSUE THREAD

**Issue by lhp1507** [arduino-libraries/NTPClient#100]
Hi everyone,
I have an issue:
I use exactly the Advance example from NTPClient library and upload it to my nodeMCU kit.
But the time is not correct (photo attached). This 
Do you know the problem? Please let me know.
Thank you!
All the best.

Here is my code:
```c++
#include <NTPClient.h>
#include <ESP8266WiFi.h>
#include <WiFiUdp.h>

const char *ssid     = "Hoang Hung 2";
const char *password = "09061997";

WiFiUDP ntpUDP;
NTPClient timeClient(ntpUDP, "0.asia.pool.ntp.org", 7*3600, 60000);

void setup(){
  Serial.begin(115200);

  WiFi.begin(ssid, password);

  while ( WiFi.status() != WL_CONNECTED ) {
    delay ( 500 );
    Serial.print ( "." );
  }

  timeClient.begin();
}

void loop() {
  timeClient.update();

  Serial.println(timeClient.getFormattedTime());

  delay(1000);
}
```

![image](https://user-images.githubusercontent.com/46106387/78047282-5bc8bd80-73a2-11ea-9404-dc79bb71cc63.png)

**Comment by IsakAlmgren** [comment]
The code looks okay. So that means that either the ntp server has incorrect time or your laptop does.
I'd bet it's your laptop time that is off, go google something like "Troubleshooting for Windows Time Service" and see if that helps. Otherwise, try switching to a different ntp pool.

**Comment by lhp1507** [comment]
Oh, Thank you 3000 for your help <3
I think it's caused exactly you said.
Respectfully,
Phu.
