### ISSUE TITLE
Bits reversed in byte 0 of initial packet sent 

### ISSUE THREAD

**Issue by pneumaticdeath** [arduino-libraries/NTPClient#110]
If you look at the spec: https://www.rfc-editor.org/rfc/rfc5905.txt you'll notice that the fields are in LSB (least significant bit first), but it looks like you interpreted them as MSB.

Look at https://github.com/arduino-libraries/NTPClient/blob/master/NTPClient.cpp#L185
Since the first byte is 0b11100011, that means that LI is 3 (which is fine), but VN is 000  and Mode is 7 (111).
I think you meant to have LI =3, VN = 4 and mode = 3, but that would be 0b01110011 expressed in MSB.

**Comment by pneumaticdeath** [comment]
Also in the version of the code that I have, there is an isValid method that also is checking the wrong bits for LI and Mode.

**Comment by pneumaticdeath** [comment]
Oops.. i misread the spec.

**Comment by SadaleNet** [comment]
I'm confused by the exact same line of code. And I've got the answer from the reference NTP implementation. Here's the relevant code:

```
/*
 * Stuff for extracting things from li_vn_mode
 */
#define	PKT_MODE(li_vn_mode)	((u_char)((li_vn_mode) & 0x7))
#define	PKT_VERSION(li_vn_mode)	((u_char)(((li_vn_mode) >> 3) & 0x7))
#define	PKT_LEAP(li_vn_mode)	((u_char)(((li_vn_mode) >> 6) & 0x3))

/*
 * Stuff for putting things back into li_vn_mode in packets and vn_mode
 * in ntp_monitor.c's mon_entry.
 */
#define VN_MODE(v, m)		((((v) & 7) << 3) | ((m) & 0x7))
#define	PKT_LI_VN_MODE(l, v, m) ((((l) & 3) << 6) | VN_MODE((v), (m)))
```

So the least significant three bits are mode (M). The next significant three bits are the version (V) and the most significant two bits are leap indicator (L). i.e. `0bLLVVVMMM`. `0b11100011` would be LI=3, V=4 and M=3.

Source: https://github.com/ntp-project/ntp/blob/master-no-authorname/include/ntp.h

**Comment by pneumaticdeath** [comment]
The Spec is written in LSB (least significant bit first), so the leftmost 3 bits are the first three (represented by values 1, 2, and 4).

**Comment by pneumaticdeath** [comment]
oops... MSB not LSB.
