### ISSUE TITLE
Tip: Use Your local router as NTP-Server if possible

### ISSUE THREAD

**Issue by ddTech** [arduino-libraries/NTPClient#127]
I always found updating the time from a NTP-Server like pool.ntp.org very time consuming and unreliable. DNS resolve takes a moment on the small ESP8266s and the request itself not seldom times out, probably due to high demand. 
Depending on the implementation, this blocks the MC more or less from its primary task. 

So I played with different providers and used ip-adresses instead of domains on subsequent calls, which makes a huge difference. However the addresses change from time to time, so this needs to be addressed in code as well.

That was until I accidentally found out that our local router - the router the esp directly connects to and that serves as the gateway - by default also provides NTP services.

So for about two years I'm now using a local address in order to update the time with 
   `IPAddress timeServerIP(192,168,84,254);`

(which is our local router address) This is stunningly fast, 99.9% reliable and more than accurate enough for (all) my needs.

As I write out the requests and differences to a log file, I can also tell You that over a time period of six hours, the time difference is always within a second. In most cases it actually is zero. The unit I am constantly watching is placed outside, i.e. not working under constand temperature conditions. Inside it's probably even better. 
Updating the time once or twice a day or even less often is probaly more than sufficient for most applications.

Conclusion: 
In order to make Your life a tiny bit more easy
- check if Your router provides NTP service by just making a NTP-call to it
- set update interval to a (much) longer interval, monitor differences for a few days and make adjustments as needed.

HTH

regards

Frank

**Comment by per1234** [comment]
Thanks for the tip @ddTech
