### ISSUE TITLE
Manually set initial date and time and then update by library

### ISSUE THREAD

**Issue by basementmedia2** [arduino-libraries/NTPClient#135]
Hi,

i'm using your library which is great.
But in my project, it may be the case the the user device has internet connection and maybe NOT has internet connection.

Is something like this possible

```
if (WiFi.status()==WL_CONNECTED) {
    timeClient.update();
    epochTime = timeClient.getEpochTime();
} else {
    timeClient.setEpochTime(myTimeValueComingFromtheDevice (e.g. mobile phone)); 
}
```
I  know that the function "setEpochTime()" does not exist, but is there a way to manually set the initial date/time which is then refreshed inside the loop?

Best wishes
Daniel

**Comment by per1234** [comment]
Hi @basementmedia2. Thanks for taking the time to submit an issue.

I see we already have a prior feature request this at https://github.com/arduino-libraries/NTPClient/issues/26.

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
