### ISSUE TITLE
Day of week

### ISSUE THREAD

**Issue by Testato** [arduino-libraries/NTPClient#14]
I believe that it is importand have a getWeekDay() method for retrieve the day of week.
It is enougth receive simply a number, from 1 to 7, that represent monday-->sunday

**Comment by FWeinb** [comment]
In 3.0.0 there will be a `getDay()` function. It will response 0 - 6, from Sunday to Saturday.

**Comment by Testato** [comment]
0-6 = Sunday to Saturday  ?

The week do not start whit sunday in every country. Is there a standard on this topic ?

**Comment by FWeinb** [comment]
I don't know of any standard. But you can just shift it to the value you want 0 to be.
