### ISSUE TITLE
Accuracy milliseconds

### ISSUE THREAD

**Issue by charlesardsilva** [arduino-libraries/NTPClient#156]
I have been using this library, now I must have accuracy in milliseconds.
It is not clear to me if I can trust in that accuracy.

I am using Arduino UNO.

Could someone help me to understand if is possible?

**Comment by per1234** [comment]
Hi @charlesardsilva. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you out over there:

https://forum.arduino.cc/
