### ISSUE TITLE
Time offsets >±32,535 seconds still busted in version 3.2.0

### ISSUE THREAD

**Issue by LeMon3half** [arduino-libraries/NTPClient#168]
Timezone is not working for those of us who live too far from Greenwich...

NTPClient.h line 76
(int timeOffset) should be long, not int

NTPClient.cpp line 143
(int timeOffset) should be long, not int

It works fine after these changes.

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @LeMon3half .

I see we have another report about this at https://github.com/arduino-libraries/NTPClient/issues/72.

Note the latest comment there from one of Arduino's firmware developers:

> can you please create a PR containing those changes?

So it seems that a pull request for the proposed changes would be the best way to move this forward.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
