### ISSUE TITLE
what will the timeClient.update() function do when there's no internet

### ISSUE THREAD

**Issue by LMJiscool** [arduino-libraries/NTPClient#182]
Will the timeClient.update() function just skip and use the old time or will the code break and the Arduino stop working ?

**Comment by per1234** [comment]
Hi @LMJiscool. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
