### ISSUE TITLE
getFormattedDate() in 3.1.0 no longer in latest3.2.1

### ISSUE THREAD

**Issue by MarcEngrie** [arduino-libraries/NTPClient#183]
Hi, 

I went through an upgrade cycle where I also upgraded this library from 3.1.0 to the latest 3.2.1. Now, all my previous apps (all of them use the NTPClient), fail to compile as the function getFormattedDate() is no longer present in the library. 

Any reason why and what your suggestted alternative is?

**Comment by per1234** [comment]
Hi @MarcEngrie. Thanks for your report. There has never been a function of this name in the official library:

https://github.com/arduino-libraries/NTPClient/blob/3.1.0/NTPClient.h

I think you must have previously installed the development version of the library from this pull request, which does add a function of that name: https://github.com/arduino-libraries/NTPClient/pull/119
