### ISSUE TITLE
Missing method

### ISSUE THREAD

**Issue by jdavid54** [arduino-libraries/NTPClient#196]
The original method included method 
String getFormattedDate(unsigned long secs = 0);
which then calls  String getFormattedTime(unsigned long secs = 0);

Why does this version 3.2.1 exclude getFormattedDate and change to getFormattedTime() const ?
 
I have changed the 3 files (h, cpp, keywords.txt) and zip for a new library.
[NTPClient-3.2.1_modified.zip](https://github.com/arduino-libraries/NTPClient/files/12874671/NTPClient-3.2.1_modified.zip)

**Comment by per1234** [comment]
Hi @jdavid54. There never was such a method in this library. If you saw one before you must have been using a different library or a unofficial modified version of the library.

There are several proposals for adding such a capability to the library:

- https://github.com/arduino-libraries/NTPClient/pull/94
- https://github.com/arduino-libraries/NTPClient/pull/119
