### ISSUE TITLE
Automatic summer/winter time change

### ISSUE THREAD

**Issue by laurent7878** [arduino-libraries/NTPClient#197]
Hi,  how to add automatic summer or winter time change? 

Thanks

**Comment by per1234** [comment]
Hi @laurent7878. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
