### ISSUE TITLE
Blocking execution and then arduino freezes

### ISSUE THREAD

**Issue by step135** [arduino-libraries/NTPClient#213]
Maybe sometimes there is problem with connection to server and loop function freezes and the board needs manual restart.

**Comment by per1234** [comment]
Hi @step135. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project, via high quality detailed issues.

Support for your report is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
