### ISSUE TITLE
getFormattedDate, getMonth and getYear missed in v3.2.1

### ISSUE THREAD

**Issue by nricciardi** [arduino-libraries/NTPClient#219]
I'm using version `3.2.1`, but there aren't `getFormattedDate`, `getMonth` and `getYear` methods.

```
error: 'class NTPClient' has no member named 'getFormattedDate'
```

Is implementation **planned**?

**Comment by per1234** [comment]
I see we already have requests for this features at https://github.com/arduino-libraries/NTPClient/issues/29, https://github.com/arduino-libraries/NTPClient/issues/86, https://github.com/arduino-libraries/NTPClient/issues/113, and https://github.com/arduino-libraries/NTPClient/issues/139.

So I'll close this as a duplicate.

@nricciardi. In the future, please take the time to search the issue tracker for existing requests before you submit an issue.

**Comment by manasouza** [comment]
@nricciardi there's a workaround for getMonth and getYear: https://github.com/arduino-libraries/NTPClient/issues/36#issuecomment-2466583385
