### ISSUE TITLE
updateInterval variable type problem between int and unsigned int

### ISSUE THREAD

**Issue by pabloandresm** [arduino-libraries/NTPClient#25]
The internal _updateInterval is an 'unsigned int' (0-65535), which allows a maximum of 65 seconds between updates when calling 'bool update()'. It is initialized to 60000 (60 seconds) by default.

The constructor of NTPClient() takes it as parameter so a user can modify it, but the parameter is declared as 'int' (32 seconds max interval) instead of 'unsigned int'.

The constructor should be also 'unsigned int' as the internal private variable _updateInterval.

Even more, I suggest to modify them both to unsigned long, to be able to set more than only 65 seconds interval update.

**Comment by sandeepmistry** [comment]
@pabloandresm thanks for pointing this out.

This definitely applies to AVR boards like the Uno, on SAMD int's are 32-bits. Changing to unsigned long makes sense.

Would you like to submit a pull request for this change?

**Comment by pabloandresm** [comment]
Yes sure. I'll do it.

**Comment by pabloandresm** [comment]
done the pullrequest

**Comment by sandeepmistry** [comment]
For other's to follow along, @pabloandresm has submitted PR #27 for this.

**Comment by sandeepmistry** [comment]
Closed via #27.
