### ISSUE TITLE
Using an IP address for NTP connections

### ISSUE THREAD

**Issue by sheffieldnick** [arduino-libraries/NTPClient#31]
I've modified NTPClient() to accept an IP address as an alternative to the usual server name. This often speeds up an NTP fetch by avoiding the DNS lookup step.

NTPClient.h:

    const char*   _poolServerName = "time.nist.gov"; // Default time server
    IPAddress     _poolServerIP;

    NTPClient(UDP& udp, int timeOffset);
    NTPClient(UDP& udp, IPAddress poolServerIP);
    NTPClient(UDP& udp, const char* poolServerName);

NTPClient.cpp:

  
    NTPClient::NTPClient(UDP& udp, IPAddress poolServerIP) {
      this->_udp            = &udp;
      this->_poolServerIP = poolServerIP;
      this->_poolServerName = NULL;
    }

      // you can send a packet requesting a timestamp:
      if (this->_poolServerName) this->_udp->beginPacket(this->_poolServerName, 123); // NTP requests are to port 123
        else this->_udp->beginPacket(this->_poolServerIP, 123);
      this->_udp->write(this->_packetBuffer, NTP_PACKET_SIZE);

**Comment by blackketter** [comment]
I think that if the server name is an IP address in the form of a string, it should just work, no?

**Comment by sheffieldnick** [comment]
Yes, I expect it would still work, but all the other Arduino libraries seem to use the binary IPAddress datatype. Presumably because it takes up slightly less memory, and the connection code can avoid the need to recognise a numeric string, and convert it to binary?

**Comment by sandeepmistry** [comment]
Hi @sheffieldnick,

That sounds like a good addition, could you please prepare a pull request for it?
