### ISSUE TITLE
Change default NTP server to pool.ntp.org ?

### ISSUE THREAD

**Issue by sheffieldnick** [arduino-libraries/NTPClient#34]
What do you think about changing the default (US-centric) `time.nist.gov` to the more flexible `pool.ntp.org` which should resolve to a region-specific NTP server from anywhere in the world, and spread the traffic load?

[http://www.pool.ntp.org/en/](url)

**Comment by Testato** [comment]
+1
Is the correct way to do

**Comment by sandeepmistry** [comment]
@sheffieldnick sounds good to me as well, could you please submit a pull request. Thanks.

**Comment by sheffieldnick** [comment]
Do you really want a pull request for such a simple change? It is only one string...

**Comment by Testato** [comment]
Github is a powerful tool for this little PR change. You can modify the string and submit a PR in two ckick.
It is useful have your name officially in tbe collaborator list

**Comment by jwktje** [comment]
Would it be hard to add a function to define the server this libary uses in my sketch?

**Comment by sandeepmistry** [comment]
Closed via #37.
