### ISSUE TITLE
get year, month, day

### ISSUE THREAD

**Issue by lutfisan** [arduino-libraries/NTPClient#36]
how to get year, month, and day?

**Comment by bvanelli** [comment]
I added a function to do exactly that, the only dependency being `#include <time.h>`.

```cpp
String NTPClient::getFullFormattedTime() {
   time_t rawtime = this->getEpochTime();
   struct tm * ti;
   ti = localtime (&rawtime);

   unsigned long year = ti->tm_year + 1900;
   String yearStr = String(year);

   unsigned long month = ti->tm_mon + 1;
   String monthStr = month < 10 ? "0" + String(month) : String(month);

   unsigned long day = ti->tm_mday;
   String dayStr = day < 10 ? "0" + String(day) : String(day);

   return yearStr + "-" + monthStr + "-" + dayStr + " " + this->getFormattedTime();
}
```

The output seems right:

`2017-07-22 19:20:25`

What you guys think? This should be added to the main code?

Best Regards.

**Comment by lutfisan** [comment]
it's work perfect, why you not update your code with this?

**Comment by Testato** [comment]
https://github.com/arduino-libraries/NTPClient/issues/3

**Comment by bvanelli** [comment]
I agree with @Testato  that this is not the purpose of the library, however this conversion is pretty useful for time-stamping and it's pretty handy to have it working out of the box, without the need for other conversions.

I also ran the benchmarks: the `getFormattedTime()` runs in about 100 microseconds, whereas `getFullFormattedTime()` is about 450 microseconds. Not very good, but not bad either.

**Comment by pwrsoft** [comment]
@sandeepmistry Could you please add the suggested changed to the library?

**Comment by Gund77** [comment]
Hi Everyone, i had a problem while adding the new public method to the NTPclient.cpp and NTPClient.h
once i added the code, the compiler gets error when processing this file.

I added the functions to the .cpp file and the header into the public section of .h file

How can i fix it?

thanks

[NTPClient.zip](https://github.com/arduino-libraries/NTPClient/files/1355644/NTPClient.zip)

**Comment by bvanelli** [comment]
@Gund77 , as I stated, my workaround makes use of the C standard time library.

You can fix it by adding ```#include <time.h>``` in your header file. Your NTPClient.h's first 6 lines should look like this:

```cpp
#pragma once

#include "Arduino.h"
#include <time.h>

#include <Udp.h>
```

**Comment by bvanelli** [comment]
For anyone that still comes to this topic seeking for help, please use the fork implementation on Github [taranais/NTPClient](https://github.com/taranais/NTPClient). He implements the function `getFormattedDate()` that returns the time formatted in ISO 8601.

**Comment by Gund77** [comment]
Sorry,  My mistate. I included Time.h library as last in the list so the compiler do not find the declaration while parsing the NTP library.
Anyway, switching the inclusions position the problem persist. i got error again. It might be a sintax error, but i cant find where...   can you please send me your NTP Client.h and .cpp files?

thank you so much.

**Comment by bvanelli** [comment]
@Gund77 , it is a syntax error... You don't use the namespace when declaring a function inside the class declaration (header file). Instead of using:

```cpp
     /**
     * @return time formatted like `DD:MM:YYYY`
     */
    String NTPClient::getFormattedDate() ;

     /**
     * @return time formatted like `DD:MM:YYYY hh:mm:ss`
     */
     String NTPClient::getFullFormattedTime(); 

   int NTPClient::getYear(); 
   int NTPClient::getMonth(); 
   int NTPClient::getDate();
```

You should declare them as:

```cpp
    /**
    * @return time formatted like `hh:mm:ss`
    */
    String getFormattedTime();

    /**
    * @return time formatted like `DD:MM:YYYY`
    */
    String getFormattedDate();

     /**
     * @return time formatted like `DD:MM:YYYY hh:mm:ss`
     */
    String getFullFormattedTime(); 

    int getYear(); 
    int getMonth(); 
    int getDate();
```

[Working version of NTPClient.zip](https://github.com/arduino-libraries/NTPClient/files/1357589/NTPClient.zip)

**Comment by thiagoarreguy** [comment]
the function getFullFormattedTime ir returnning time formatted like `YYYY:MM:DD hh:mm:ss`

**Comment by icandura** [comment]
@thiagoarreguy I consider that replacing an NTP server is a good choice.

**Comment by Moerbius** [comment]
Hi,

Does it take into account the leap years?

**Comment by kaefert** [comment]
Since I didn't want to modify the library, I adapted the code snippet to work inside main.cpp:

```
// https://github.com/arduino-libraries/NTPClient/issues/36
String getTimeStampString() {
   time_t rawtime = timeClient.getEpochTime();
   struct tm * ti;
   ti = localtime (&rawtime);

   uint16_t year = ti->tm_year + 1900;
   String yearStr = String(year);

   uint8_t month = ti->tm_mon + 1;
   String monthStr = month < 10 ? "0" + String(month) : String(month);

   uint8_t day = ti->tm_mday;
   String dayStr = day < 10 ? "0" + String(day) : String(day);

   uint8_t hours = ti->tm_hour;
   String hoursStr = hours < 10 ? "0" + String(hours) : String(hours);

   uint8_t minutes = ti->tm_min;
   String minuteStr = minutes < 10 ? "0" + String(minutes) : String(minutes);

   uint8_t seconds = ti->tm_sec;
   String secondStr = seconds < 10 ? "0" + String(seconds) : String(seconds);

   return yearStr + "-" + monthStr + "-" + dayStr + " " +
          hoursStr + ":" + minuteStr + ":" + secondStr;
}
```

**Comment by lxrobotics** [comment]
I am closing this issue since there are solutions available as code snippets as well as in user-forks. It would be great if some brave soul would create a pull request so that we can add this functionality to this library as well.

**Comment by jimmisitepu88** [comment]
> Hi Everyone, i had a problem while adding the new public method to the NTPclient.cpp and NTPClient.h
> once i added the code, the compiler gets error when processing this file.
> 
> I added the functions to the .cpp file and the header into the public section of .h file
> 
> How can i fix it?
> 
> thanks
> 
> [NTPClient.zip](https://github.com/arduino-libraries/NTPClient/files/1355644/NTPClient.zip)

I have fix your code, you can download this file
[NTPClient.tar.gz](https://github.com/arduino-libraries/NTPClient/files/5718702/NTPClient.tar.gz)

**Comment by id1402** [comment]
Hello.
I tried [NTPClient.tar.gz](https://github.com/arduino-libraries/NTPClient/files/5718702/NTPClient.tar.gz) made by [jimmisitepu88](https://github.com/jimmisitepu88).

Unfortunately timeClient.getFormattedTime() results in wrong date:
Yesterday: ```00:21:53.687 -> 2053-03-15```
Should be 2023-03-15.

Today:  ```12:56:50.757 -> 2053-03-16```
Should be 2023-03-16

The time shown left is local time UTC+1, when timeClient.getFormattedTime() is called.
It would be great if some brave soul would fix this.

**Comment by iAvoe** [comment]
For those who is developing a IoT project right now without replacing NTPClient, and without much C++ background, just put this in between the `#define` s and void `setup()`, or it should be similar to this:

```
const long myUTCTimeOffset = <UTC zone code> + 3600;
WiFiUDP ntpUDP;
const char* myNTPServer = "time.google.com";

/**
 * Adding support to year, month, day from NTPClient
 * Credit: https://github.com/arduino-libraries/NTPClient/issues/36
 * Credit: https://www.geeksforgeeks.org/inheritance-in-c/
 */
class ExtendedNTPClient : public NTPClient {
public:
    ExtendedNTPClient(WiFiUDP &udp, const char *server, long timeOffset)
        : NTPClient(udp, server, timeOffset) {}

    int getYear() {
        time_t rawtime = this->getEpochTime();
        struct tm *ti;
        ti = localtime(&rawtime);
        int year = ti->tm_year + 1900;
        return year;
    }

    int getMonth() {
        time_t rawtime = this->getEpochTime();
        struct tm *ti;
        ti = localtime(&rawtime);
        int month = ti->tm_mon + 1; // tm_mon starts from 0
        return month;
    }

    int getDay() {
        time_t rawtime = this->getEpochTime();
        struct tm *ti;
        ti = localtime(&rawtime);
        int day = ti->tm_mday;
        return day;
    }
};
ExtendedNTPClient timeClient(myNTPUDP, myNTPServer, myUTCTimeOffset);
```
