### ISSUE TITLE
setPoolServerName

### ISSUE THREAD

**Issue by vincentVDB** [arduino-libraries/NTPClient#48]
hello,
I loaded today the NTPClient by the IDE Arduino

1/ Not colored word : 
setTimeOffset
setUpdateInterval
setPoolServerName 
Cause : It's missing ! I send the pull request for added in keywords.txt

2/ compilation error :
344:  timeClient.setPoolServerName("europe.pool.ntp.org");
'class NTPClient' has no member named 'setPoolServerName'
Cause: setPoolServerName is missing in the cpp file of the library

weird because setPoolServerName is present here in the cpp file !

**Comment by ingegno** [comment]
not a bug, but can you please do a 3.1.1 release to make it easy to install for novice users. I require the setting of IP in a project...

**Comment by lxrobotics** [comment]
[3.2.0](https://github.com/arduino-libraries/NTPClient/releases/tag/3.2.0) has been resolved which should fix this issue.
