### ISSUE TITLE
Working an Ethernet Shield aka Non-wifi

### ISSUE THREAD

**Issue by memphis2k** [arduino-libraries/NTPClient#54]
Could some provide the code for the default example using a Arduino Ethernet Sheild, instead of the Wifi adapter?

Ethernet.h I believe it is.

Thanks,

**Comment by pyprism** [comment]
https://www.arduino.cc/en/Tutorial/UdpNtpClient

**Comment by lxrobotics** [comment]
Closing this since the question was answered.

BTW the forum is more suited for this kind of questions: https://forum.arduino.cc/
