### ISSUE TITLE
NTPClient library - How does timeClient.update() work

### ISSUE THREAD

**Issue by RayBright** [arduino-libraries/NTPClient#57]
Using a ESP8266-12E  I've been trying the Network Time Protocol (NTP) but have discover an unexplained issue as follows:

Using say the example sketch that comes with the library 'basic.ino'  I find the time displayed updates even when I shut down my WiFi as follows:

void loop() {
  timeClient.update();
  Serial.println(timeClient.getFormattedTime());
  delay(1000);
}   

My expectation is that timeClient.update() should fail but the sketch seems to keep accumulating/updating and displaying time by itself.

I've been unable to find a manual/instructions for library NTPClient.

Assistance / comments welcome.

**Comment by jbrown123** [comment]
Note that NTPClient::update returns a boolean indicating whether updating was successful (true=success). Also, note that it will only attempt an update every updateInterval ms (60000 ms or 60 seconds by default).  The only time this call will return false is when it actually attempted to do an update, and that update failed.

**Comment by lxrobotics** [comment]
As far as I can see @RayBright 's comment should be resolved by the answers provided by @iafilius and @jbrown123 . If not, please reopen this issue.
