### ISSUE TITLE
not working with static IP on esp8266

### ISSUE THREAD

**Issue by Necrosaurus** [arduino-libraries/NTPClient#58]
Thanks for this library, unfortunately I cant get it to work when i have a static IP assigned (in the script) to my ESP8266. Is there something I'm doing wrong or an easy way around this (other than setting the IP on the router). 
Any help appreciated
thanks

**Comment by freeck** [comment]
Did you try something like this? It worked for me.
`setup(){
		WiFi.begin(ssid, password);
		IPAddress ip1 = ipaddr_addr("192.168.0.202");
		IPAddress ip2 = ipaddr_addr("192.168.0.1");
		IPAddress ip3 = ipaddr_addr("255.255.255.000");
		IPAddress ip4 = ipaddr_addr( "8.8.8.8" );//dns 1
		IPAddress ip5 = ipaddr_addr( "8.8.4.4" );//dns 2
		if ( ip1 != 0 ){
			WiFi.config(ip1, ip2, ip3, ip4, ip5);
		} 
		while (WiFi.status() != WL_CONNECTED) {
			delay(500);
			Serial.print(".");
		}
		timeClient.begin();
	}
}
void loop() 
{
	if (timeClient.update())
		ets_printf("OK\n");
	ets_printf(timeClient.getFormattedTime().c_str());
	ets_printf("%d\n",timeClient.getEpochTime());
	delay(1000);
}

**Comment by Necrosaurus** [comment]
Thanks freeck! 
adding the 2 dns variables to the wifi.config fixed it, thanks!

**Comment by lxrobotics** [comment]
Closing this issue since the question has been answered.

**Comment by Jhonvalencia77** [comment]
Thanks! Days trying to find the solution to the same problem and the solutions was the **** DNS. (Y)

**Comment by Quercuz** [comment]
If you use Arduino IDE with <ESP8266WiFi.h> there is a different order for the arguments in the config-statement See the comment in the source code:   _//ESP argument order is:  ip, gateway, subnet, dns1 
  //Arduino arg order is:  ip, dns, gateway, subnet._

So after lots of trouble i changed my config in WiFi.config(STATICIP, DNS1, GATEWAY, SUBNET) and everything works smooth now. The comment means that if you use ESP-IDE (?) the argument order is:  ip, gateway, subnet, dns1. When you use Aduino IDE (for ESP8266) the argument order is:  ip, dns, gateway, subnet._
