### ISSUE TITLE
NTPClient can't connect

### ISSUE THREAD

**Issue by pfeno** [arduino-libraries/NTPClient#59]
Hi

I've used the library with an ESP32 DevKit  V1 and with the sample code it didn't work .
I just update the line `NTPClient timeClient(ntpUDP)` by a more suitable for my case `NTPClient timeClient(ntpUDP, "ntp.unice.fr");` from my university or `fos-dca-01.av.si-aceralia`.

 Same result, didn't work 

Could you help me ?
Regards

**Comment by joeybab3** [comment]
Are you sure that the wifi is able to connect successfully?
