### ISSUE TITLE
SIM800 GSM

### ISSUE THREAD

**Issue by oleslavs** [arduino-libraries/NTPClient#63]
Hello! Please help!
I`m using SIM800 GSM via TinyGSMclient library, but no examples of code how use NTPClient in my case. 
I`m search a lot but not found how tu use udp: Reference to an UDP object with TinyGSMclient.h.
Is exist many examples of ethernet or wi-fi but none of GSM.

**Comment by lxrobotics** [comment]
Hi @oleslavs :wave: Maybe you've found a solution by now, in any case such questions are best taken to the [forum](https://forum.arduino.cc/) which is better suited for this type of questions.
