### ISSUE TITLE
NTP returns erroneous times

### ISSUE THREAD

**Issue by oh2xx** [arduino-libraries/NTPClient#65]
Running the NTP Basic example gave me the following values:

07:00:14
07:00:15
07:00:16
07:00:17
07:00:18
07:00:19
07:00:20
07:00:21
07:00:22
06:59:43  <---- What is happening here?
06:59:44
06:59:45
06:59:46
06:59:47
06:59:48
06:59:49
06:59:50
06:59:51
06:59:52
06:59:53
06:59:54
06:59:55
06:59:56
06:59:57
06:59:58
06:59:59
07:00:00
07:00:01

And this is the NTP Basic example I used:

#include <NTPClient.h>
// change next line to use with another board/shield
#include <ESP8266WiFi.h>
//#include <WiFi.h> // for WiFi shield
//#include <WiFi101.h> // for WiFi 101 shield or MKR1000
#include <WiFiUdp.h>

const char *ssid     = "xxxxx";
const char *password = "xxxxx";

WiFiUDP ntpUDP;
NTPClient timeClient(ntpUDP);

void setup(){
  Serial.begin(115200);

  WiFi.begin(ssid, password);

  while ( WiFi.status() != WL_CONNECTED ) {
    delay ( 500 );
    Serial.print ( "." );
  }

  timeClient.begin();
}

void loop() {
  timeClient.update();

  Serial.println(timeClient.getFormattedTime());

  delay(1000);
}

**Comment by bill-orange** [comment]
I have not checked for relatively small error like what you noticed.  What I have found is that I still occasionally get a year of 1970, even with precautions. I happens once in every 50 or so calls.

```
NTP.begin("pool.ntp.org", TIMEZONE, false);
  delay(100);
  NTP.setInterval(63);
    
  while ((year(now()) < 1980) || (year(now()) > 2035)) {
    int i;
    delay (500);
    Serial.print("+");
    NTP.begin("pool.ntp.org", TIMEZONE, false);
    i++;
    if (i > 60) {
      reboot();
    }
  }

  NTP.getTime();                  // Needed first call to now() in Loop to work
  delay(2000);                    // 

  //diagnostics
  Serial.println (" ");
  Serial.print("Current Year "); Serial.println(year(now()));
```

**Comment by lxrobotics** [comment]
Hi @oh2xx - probably caused by stale packets stored in the packet buffer - fixed in https://github.com/arduino-libraries/NTPClient/commit/18d4ac7eb15d9225bdfa166f7d5e4ec0598e5670 .
