### ISSUE TITLE
DST time

### ISSUE THREAD

**Issue by StoyanVP** [arduino-libraries/NTPClient#69]
Hello,
can it be used DST?

**Comment by lxrobotics** [comment]
@StoyanVP as far as I am aware NTP utilizes [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) which does not include [DST](https://en.wikipedia.org/wiki/Daylight_saving_time).

BTW the forum is more suited for this kind of questions: https://forum.arduino.cc/

**Comment by probonopd** [comment]
The Timezone library can be used  to achieve this.
It is available on GitHub at the following URL: https://github.com/JChristensen/Timezone

You can download the library from there and install it in your Arduino IDE by following these steps:

- Download the library as a zip file from GitHub.
- In the Arduino IDE, go to Sketch > Include Library > Add .ZIP Library...
- Navigate to the zip file you downloaded and select it.
- The library should now be installed and you can use the Timezone class in your sketches.

For example, Germany observes DST from the last Sunday in March to the last Sunday in October. To handle this correctly, you can use the Timezone library and set up your NTPClient object accordingly.

Here's an example sketch that uses the Timezone library to print the local time every second, including DST for German time:

```
#include <ESP8266WiFi.h>
#include <NTPClient.h>
#include <WiFiUdp.h>
#include <Timezone.h>

// Replace with your network credentials
const char* ssid = "your_SSID";
const char* password = "your_PASSWORD";

WiFiUDP udp;
NTPClient ntpClient(udp, "pool.ntp.org", 0); // NTP client object
TimeChangeRule CEST = {"CEST", Last, Sun, Mar, 2, 120};  // Central European Summer Time
TimeChangeRule CET = {"CET ", Last, Sun, Oct, 3, 60};     // Central European Standard Time
Timezone timezone(CEST, CET);  // Timezone object for Germany

void setup() {
  Serial.begin(115200);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(1000);
    Serial.println("Connecting to WiFi...");
  }

  Serial.println("Connected to WiFi");

  ntpClient.begin(); // Start the NTP client
  ntpClient.update(); // Force an update to get the time
}

void loop() {
  time_t utc = ntpClient.getEpochTime(); // Get the current UTC time from the NTP client
  time_t local = timezone.toLocal(utc); // Convert the UTC time to local time
  Serial.println(ctime(&local)); // Print the local time
  delay(1000);
  ntpClient.update(); // Update the NTP client
}

```

**Comment by aentinger** [comment]
Thank you @probonopd for providing this update. It's certainly useful for the next person to come along =)
