### ISSUE TITLE
Can you please create a new release

### ISSUE THREAD

**Issue by dushyantahuja** [arduino-libraries/NTPClient#74]
PlatformIO is currently pulling release 3.1.0 - and that does not have the setPoolServerName function. Please create a new release from the master so that the libraries can be updated in PlatformIO

**Comment by lxrobotics** [comment]
Hi @dushyantahuja :wave: I've created a new release under https://github.com/arduino-libraries/NTPClient/releases/tag/3.2.0 so this issue should be fixed :wink:

**Comment by dushyantahuja** [comment]
Thanks
