### ISSUE TITLE
Changes for 3.0.0

### ISSUE THREAD

**Issue by FWeinb** [arduino-libraries/NTPClient#9]
I just merged #8 which sets the basis for 3.0.0. Are there any other things we need to change for this release. We can change the API as we like because we are doing a major version bump, so getting the API straight is important.

**Comment by sandeepmistry** [comment]
I think we should add an ```end()``` API which calls ```.stop()``` on the UDP socket.

We could also add a ```begin()``` and ```begin(port)``` API to override the port used. Maybe these can be optional?

**Comment by FWeinb** [comment]
Adding `end()` sounds good. But I don't see the reason for `begin`, any idea why an NTP server should run on a port different from 123?

**Comment by sandeepmistry** [comment]
Sorry, this was to set the local UDP port: [``_port``](https://github.com/arduino-libraries/NTPClient/blob/master/NTPClient.h#L15).

**Comment by FWeinb** [comment]
Sure that could be handy to change, good point.

**Comment by sandeepmistry** [comment]
I'll get a PR done for this today.

**Comment by sandeepmistry** [comment]
We also need to change the ```keywords.txt``` file, the IDE expects hard tabs instead of spaces.

**Comment by FWeinb** [comment]
Didn't know that the IDE expects hard tabs there. Good to know. Did you change that in #10?

**Comment by sandeepmistry** [comment]
> Did you change that in #10?

No, I'll make the changes on master once #10 is merged.

**Comment by sandeepmistry** [comment]
We should also add a ```getEpochTime()``` API.

**Comment by sandeepmistry** [comment]
> We should also add a getEpochTime() API.

I think this is might be what ```getRawTime()``` returns, but I need to double check tomorrow. I had to adjust the raw time by 70 years for this other library I was using with the NTPClient.

**Comment by sandeepmistry** [comment]
I found out what was going on, I was creating an ``NTPClient`` as a local var instead of global. So, ```_timeOffset``` was not initialized to zero. I've correct this in 89aa3359a29cca518a6e395e156e5e71e2af876b.

I think it would be worthwhile to also have a ```getEpochTime()``` API that is an alias to ```getRawTime()```. PR coming shortly for this.

**Comment by sandeepmistry** [comment]
@FWeinb can we merge #11, #12, and #13 are tag another release? Or are there other changes that are needed?

cc/ @obsoleted

**Comment by FWeinb** [comment]
Looks all good! Thanks for your help!

**Comment by sandeepmistry** [comment]
Cool! I've merged them in and also added a [CHANGELOG](https://github.com/arduino-libraries/NTPClient/blob/master/CHANGELOG).

I'll aim to tag a new 3.0.0 release early next week.

**Comment by FWeinb** [comment]
Great! This is looking very good. I have to thank you a ton for doing all the work. :+1:

**Comment by FWeinb** [comment]
I just looked at the current API and think we should change all [these function](https://github.com/arduino-libraries/NTPClient/blob/master/NTPClient.cpp#L110-L121) to return integers instead of strings.

**Comment by sandeepmistry** [comment]
> I just looked at the current API and think we should change all these function to return integers instead of strings.

@FWeinb yes this makes sense, I've gone ahead and submitted #15.

**Comment by sandeepmistry** [comment]
Is there anything else we need to get done before tagging a new release?

**Comment by FWeinb** [comment]
That should it be. Thanks for the help!

**Comment by sandeepmistry** [comment]
v3.0.0 has been released.

@FWeinb thanks for reviewing the API changes in this release!

**Comment by FWeinb** [comment]
Great! Trank you for all your work.
